name: MongoDB Backup

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up MongoDB Tools
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-database-tools
    
    - name: Backup MongoDB
      run: |
        mongodump --uri="${{ secrets.MONGODB_URI }}" --out=./backup
    
    - name: Commit and Push
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add backup/
        git commit -m "Backup MongoDB data - $(date '+%Y-%m-%d')"
        git push
